// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE9ho105xG5h9E5zJVj-TqM7s94Xaaqdc',
    appId: '1:576132899763:web:8faec759d815de2b51a1c6',
    messagingSenderId: '576132899763',
    projectId: 'kripto-keren',
    authDomain: 'kripto-keren.firebaseapp.com',
    storageBucket: 'kripto-keren.firebasestorage.app',
    measurementId: 'G-MM9WWL48VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJUdeQSGpH4Jp3AmafHiwZ4X-gpWOFt4s',
    appId: '1:576132899763:android:a6272154a77b8a7051a1c6',
    messagingSenderId: '576132899763',
    projectId: 'kripto-keren',
    storageBucket: 'kripto-keren.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBTSXtwiP5brdbf5ZvRoQooFiwgGmhlQ',
    appId: '1:576132899763:ios:5468b4705d863f6851a1c6',
    messagingSenderId: '576132899763',
    projectId: 'kripto-keren',
    storageBucket: 'kripto-keren.firebasestorage.app',
    iosBundleId: 'com.tugas.akhir.kripto.tugasAkhirKripto',
  );
}
